### ISSUE TITLE
Call to a member function getName() on null

### ISSUE THREAD

**Issue by curtisdelicata** [cgdprojects/laravel-gedcom#72]
[2022-12-15 17:59:14] local.ERROR: Call to a member function getName() on null {"exception":"[object] (Error(code: 0): Call to a member function getName() on null at /home/familytree365/domains/api.familytree365.com/genealogy/vendor/cgdprojects/laravel-gedcom/src/Utils/ParentData.php:69)
[stacktrace]
#0 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/cgdprojects/laravel-gedcom/src/Utils/GedcomParser.php(208): FamilyTree365\\LaravelGedcom\\Utils\\ParentData::getPerson()
#1 /home/familytree365/domains/api.familytree365.com/genealogy/app/Jobs/ImportGedcom.php(56): FamilyTree365\\LaravelGedcom\\Utils\\GedcomParser->parse()
#2 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ImportGedcom->handle()
#3 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#7 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#8 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#9 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#11 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#12 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#13 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#15 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#16 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#17 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()
#18 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#19 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#20 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(146): Illuminate\\Queue\\Worker->daemon()
#21 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#22 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#23 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#27 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call()
#28 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#29 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#30 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/symfony/console/Application.php(1020): Illuminate\\Console\\Command->run()
#31 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/symfony/console/Application.php(312): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#33 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#34 /home/familytree365/domains/api.familytree365.com/genealogy/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#35 /home/familytree365/domains/api.familytree365.com/genealogy/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
"}

**Comment by curtisdelicata** [comment]
Call to a member function getName() on array {"exception":"[object] (Error(code: 0): Call to a member function getName() on array at.

This also happens for other files now.
